DROP TABLE ESTUDIANTES;
DROP TABLE CARRERAS;

CREATE TABLE ESTUDIANTES
(
  ID NUMBER PRIMARY KEY NOT NULL,
  MATRICULA VARCHAR2(9) NOT NULL,
  NOMBRES VARCHAR2(50) NOT NULL,
  APELLIDOS VARCHAR2(50) NOT NULL,
  PLANT NUMBER NOT NULL,
  IDCARRERA NUMBER NOT NULL
);

CREATE TABLE CARRERAS
(
  ID NUMBER PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR2(80) NOT NULL

);

GRANT UNLIMITED TABLESPACE TO SYSTEM;

ALTER TABLE ESTUDIANTES ADD CONSTRAINT FK_ESTUDIANTE_CARRERA FOREIGN KEY(IDCARRERA)
REFERENCES CARRERAS(ID);

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CONST_studiante_matricula UNIQUE(MATRICULA);

ALTER TABLE ESTUDIANTES ADD CONSTRAINT CK_PLANT_ESTUDIANTE 
CHECK (PLANT IN(11,12,13,14,15));

INSERT INTO CARRERAS(ID, NOMBRE)VALUES
(1,'INFORMATICA');
INSERT INTO CARRERAS(ID, NOMBRE)VALUES
(2,'LENGUA ESPAÑOLA');
INSERT INTO CARRERAS(ID, NOMBRE)VALUES
(3,'MATEMATICA');

INSERT INTO ESTUDIANTES(ID,MATRICULA,NOMBRES, APELLIDOS, PLANT,IDCARRERA)VALUES
(70,100269158,'Jose','Casanova Lorenzo',14,3);

UPDATE CARRERAS SET CARRERAS.ID = 5
WHERE CARRERAS.ID = 1;

DELETE FROM ESTUDIANTES WHERE ESTUDIANTES.ID = 1;
DELETE FROM CARRERAS WHERE CARRERAS.ID = 2;
---------------------------------------------------
CREATE TABLE ESTUDIANTE_AUDIT
(
  MatStud Varchar2(20),
  Old_User Varchar2(20),
  user_name  Varchar2(20),
  date_inscripcion DATE ,
  operacion  Varchar2(20)
);

SET SERVEROUTPUT ON;
-------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER Estudiante_after_insert
AFTER INSERT ON ESTUDIANTES
FOR EACH ROW
ENABLE
DECLARE
   v_username varchar2(20);
   v_date DATE;
BEGIN
--- Find username of person performing the INSERT into the table
SELECT USER,SYSDATE INTO v_username, v_date FROM dual;
 -- Insert record into audit table
IF INSERTING THEN
   INSERT INTO ESTUDIANTE_AUDIT
   (MatStud, Old_User, user_name, date_inscripcion, operacion)
   VALUES(:NEW.ID, NULL ,v_username, v_date, 'Insert' );
   END IF;
END;
/
---------------------------------------------------------------------------
DROP TABLE ESTUDIANTE_AUDIT;
DROP TABLE ESTUDIANTES;
DROP TRIGGER Estudiante_after_insert;

select * from Estudiante_Audit;